### PR TITLE
drop camlp4

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by hcarty** [comment]
This doesn't work for me when I build locally with `--enable-all`.  It looks like `_oasis` hasn't been updated yet to build the ppx extension.

**Comment by vbmithr** [comment]
I'm unable to reproduce. Works like a charm for me.

**Comment by hcarty** [comment]
It was an opam switch mixup on my end - sorry for the noise!  It works for me too.

**Comment by orbifx** [comment]
So will be accepted @hcarty ?

**Comment by Leonidas-from-XIV** [comment]
I have fixed the merge conflicts with current master in a branch, if you want you can just pull from there: https://github.com/Leonidas-from-XIV/msgpack-ocaml/tree/drop-camlp4

**Comment by mzp** [comment]
I merged from https://github.com/Leonidas-from-XIV/msgpack-ocaml/tree/drop-camlp4.

Thanks and sorry for delayed merge.

**Pull request merged**
